import type { KnipConfig } from "knip";

const config: KnipConfig = {
  ignore: [
    "packages/nx/package.json",
    "packages/core/package.json",
    "packages/prettier/jest.config.cts",
  ],
  ignoreBinaries: ["tsx", "cz", "commitlint", "uncomment", "tasklist", "ps"],
  includeEntryExports: false,
  rules: {
    unresolved: "off",
    exports: "off",
    types: "off",
    duplicates: "off",
  },
  workspaces: {
    ".": {
      entry: [
        "eslint.config.ts",
        "commitlint.config.ts",
        "cspell.config.json",
        "doit.config.ts",
        "index.ts",
        "jest.preset.js",
        "markdownlint.config.ts",
        "remark.config.ts",
      ],
      project: ["*.ts", "*.js"],
      ignoreDependencies: [
        "@nx/*",
        "jest-environment-*",
        "ts-node",
        "tslib",
        "jsdom",
        "jsonc-eslint-parser",
        "@swc/*",
        "@playwright/test",
        "eslint-plugin-playwright",
        "eslint",
        "@babel/core",
        "@cedric-ruiu/stylelint-config",
        "@commitlint/format",
        "@cspell/eslint-plugin",
        "@eslint/compat",
        "@eslint/js",
        "@eslint/markdown",
        "@napi-rs/cli",
        "@napi-rs/wasm-runtime",
        "@naxodev/gonx",
        "@pnpm/core",
        "@primer/stylelint-config",
        "@tailwindcss/vite",
        "@types/react",
        "@types/react-dom",
        "automd",
        "c12",
        "conventional-changelog-atom",
        "emnapi",
        "esbuild",
        "eslint-plugin-json-schema-validator",
        "eslint-plugin-jsonc",
        "eslint-plugin-mdx",
        "eslint-plugin-n",
        "eslint-plugin-oxlint",
        "eslint-plugin-perfectionist",
        "eslint-plugin-prettier",
        "eslint-plugin-regexp",
        "eslint-plugin-sonarjs",
        "eslint-plugin-yml",
        "globals",
        "jest-util",
        "mdsvex",
        "oxlint-tsgolint",
        "postcss-html",
        "prettier-plugin-tailwindcss",
        "remark-preset-lint-markdown-style-guide",
        "stylelint-config-html",
        "stylelint-config-recommended",
        "stylelint-config-standard",
        "stylelint-config-tailwindcss",
        "stylelint-prettier",
        "ts-jest",
        "typescript-eslint",
        "vite",
        "@4hse/astro-llms-txt",
        "@astrojs/check",
        "@astrojs/mdx",
        "@astrojs/partytown",
        "@astrojs/react",
        "@astrojs/sitemap",
        "astro-favicons",
        "astro-pagefind",
        "ofetch",
        "remark-collapse",
        "remark-toc",
        "tailwindcss",
      ],
    },
    "packages/*": {
      entry: ["src/index.ts"],
      project: ["src/**/*.ts"],
    },
    "packages/docs": {
      entry: ["astro.config.mjs"],
      project: ["src/**/*"],
    },
    "packages/prettier": {
      project: ["src/**/*.ts", "jest.config.cts"],
    },
    "packages/nx": {
      entry: ["src/index.ts", "src/generators/**/*.ts", "src/tools/**/*.ts"],
      project: ["src/**/*.ts", "src/tools/**/*.ts"],
      ignoreDependencies: ["@pjt/core"],
    },
    "packages/schemas": {
      ignoreDependencies: ["@pjt/core"],
    },
    "packages/opencode": {
      entry: ["plugin/**/*.ts", "tool/**/*.ts"],
      project: ["**/*.ts", "**/*.json"],
    },
  },
};

export default config;
